name: reusekit
description: A new Flutter project.
publish_to: 'none' 
version: 0.0.10
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter 
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  json_annotation: ^4.8.1
  intl: ^0.19.0
  google_fonts: ^6.1.0
  material_design_icons_flutter: ^7.0.7296
  image_picker: ^1.1.2
  uuid: ^4.5.1
  cached_network_image: ^3.3.1
  permission_handler: ^12.0.0+1
  geolocator: ^13.0.1
  flutter_map: ^8.1.1
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.1.6
  blur: ^4.0.0
  flutter_svg: ^2.0.5 
  custom_clippers: ^2.0.0
  flutter_markdown: ^0.7.1
  qr_flutter: ^4.0.0
  path_provider: ^2.0.11
  flutter_animate: ^4.1.1+1
  flutter_staggered_grid_view: ^0.7.0
  flutter_inappwebview: ^6.0.0
  screenshot: ^3.0.0
  syncfusion_flutter_calendar: ^29.1.38
  google_maps_flutter: ^2.6.0
  youtube_player_flutter: ^9.1.1
  syncfusion_flutter_charts: ^29.1.38
  alarm: ^5.1.1
  audioplayers: ^6.1.0
  vibration: ^3.1.3
  flutter_tts: ^4.2.0
  widgets_to_image: ^1.0.0
  speech_to_text: ^7.0.0
  connectivity_plus: ^6.1.0
  open_file: ^3.5.10
  flutter_quill: ^11.2.0
  vsc_quill_delta_to_html: ^1.0.5
  flutter_quill_delta_from_html: ^1.5.0
  flutter_widget_from_html: ^0.16.0
  photo_view: ^0.15.0
  latlong2: any
  dio: ^5.7.0
  font_awesome_flutter: ^10.8.0
  table_calendar: ^3.1.3
  file_picker: ^10.1.2
  syncfusion_flutter_gauges: ^29.1.38
  googleapis_auth: ^1.6.0
  googleapis: ^11.4.0
  gsheets: ^0.5.0
  path: ^1.9.0
  timeago: ^3.5.0
  flutter_local_notifications: ^19.1.0
  pdf: ^3.10.7
  timezone: ^0.10.0
  shared_preferences: ^2.2.1 
  share_plus: ^10.1.4
  supabase_flutter: ^2.9.0
  get_it: ^8.0.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
flutter:
  generate: true
  uses-material-design: true